"""
utils/email_sender.py
Sends generated PDF reports via SMTP email.
Reads credentials from st.secrets.
"""

import smtplib
import ssl
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

import streamlit as st


# ─────────────────────────────────────────────
# EMAIL BODY TEMPLATES
# ─────────────────────────────────────────────

def _build_email_body(
    patient_name: str,
    center_name: str,
    clinician_name: str,
    language: str,
) -> tuple[str, str]:
    """Return (subject, body) tuple."""
    gen_date = datetime.now().strftime("%B %d, %Y")

    if language == "Arabic":
        subject = f"تقرير التقييم النفسي — {patient_name or 'المريض'}"
        body = f"""
<html>
<body dir="rtl" style="font-family: Arial, sans-serif; color: #1e293b; direction: rtl;">
    <div style="max-width: 600px; margin: auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 10px;">
        <div style="background: linear-gradient(135deg, #1e3a5f, #2563eb); padding: 20px; border-radius: 8px; text-align: center; margin-bottom: 24px;">
            <h2 style="color: white; margin: 0;">تقرير التقييم النفسي</h2>
            {f'<p style="color: #bfdbfe; margin: 4px 0 0 0;">{center_name}</p>' if center_name else ''}
        </div>

        <p>السادة الكرام،</p>
        <p>يسرنا إرسال تقرير التقييم النفسي المرفق.</p>

        <div style="background: #f0f4ff; border-radius: 8px; padding: 16px; margin: 16px 0;">
            <table style="width: 100%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 6px; font-weight: bold; color: #64748b; width: 40%;">المريض</td>
                    <td style="padding: 6px;">{patient_name or '—'}</td>
                </tr>
                <tr>
                    <td style="padding: 6px; font-weight: bold; color: #64748b;">تاريخ التقرير</td>
                    <td style="padding: 6px;">{gen_date}</td>
                </tr>
                {f'<tr><td style="padding: 6px; font-weight: bold; color: #64748b;">الأخصائي</td><td style="padding: 6px;">{clinician_name}</td></tr>' if clinician_name else ''}
            </table>
        </div>

        <p>يرجى الاطلاع على التقرير المرفق (PDF).</p>
        <p style="color: #ef4444; font-size: 0.85em;">
            <strong>تنبيه:</strong> هذا التقرير سري وللاستخدام المهني فقط.
        </p>

        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;">
        <p style="font-size: 0.8em; color: #94a3b8; text-align: center;">
            تم إنشاؤه بواسطة PsychReport AI
        </p>
    </div>
</body>
</html>
"""
    else:
        subject = f"Psychological Assessment Report — {patient_name or 'Patient'}"
        body = f"""
<html>
<body style="font-family: Arial, sans-serif; color: #1e293b;">
    <div style="max-width: 600px; margin: auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 10px;">
        <div style="background: linear-gradient(135deg, #1e3a5f, #2563eb); padding: 20px; border-radius: 8px; text-align: center; margin-bottom: 24px;">
            <h2 style="color: white; margin: 0;">Psychological Assessment Report</h2>
            {f'<p style="color: #bfdbfe; margin: 4px 0 0 0;">{center_name}</p>' if center_name else ''}
        </div>

        <p>Dear Recipient,</p>
        <p>Please find attached the psychological assessment report as requested.</p>

        <div style="background: #f0f4ff; border-radius: 8px; padding: 16px; margin: 16px 0;">
            <table style="width: 100%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 6px; font-weight: bold; color: #64748b; width: 40%;">Patient</td>
                    <td style="padding: 6px;">{patient_name or '—'}</td>
                </tr>
                <tr>
                    <td style="padding: 6px; font-weight: bold; color: #64748b;">Report Date</td>
                    <td style="padding: 6px;">{gen_date}</td>
                </tr>
                {f'<tr><td style="padding: 6px; font-weight: bold; color: #64748b;">Clinician</td><td style="padding: 6px;">{clinician_name}</td></tr>' if clinician_name else ''}
            </table>
        </div>

        <p>Please review the attached PDF report at your earliest convenience.</p>
        <p style="color: #ef4444; font-size: 0.85em;">
            <strong>Confidentiality Notice:</strong> This report contains privileged information
            intended solely for the named recipient. If you are not the intended recipient,
            please delete this email immediately.
        </p>

        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;">
        <p style="font-size: 0.8em; color: #94a3b8; text-align: center;">
            Generated by PsychReport AI
        </p>
    </div>
</body>
</html>
"""
    return subject, body


# ─────────────────────────────────────────────
# MAIN SEND FUNCTION
# ─────────────────────────────────────────────

def send_report_via_email(
    recipient_email: str,
    pdf_bytes: bytes,
    patient_name: str,
    center_name: str,
    clinician_name: str,
    language: str,
    pdf_filename: str = "psychological_assessment_report.pdf",
) -> tuple[bool, str]:
    """
    Send the PDF report via Gmail SMTP.

    Returns:
        (success: bool, message: str)
    """
    # Get credentials from secrets
    try:
        email_user = st.secrets["EMAIL_USER"]
        email_pass = st.secrets["EMAIL_PASS"]
    except (KeyError, FileNotFoundError):
        return False, (
            "Email credentials not configured. "
            "Please add EMAIL_USER and EMAIL_PASS to your Streamlit secrets."
        )

    if not email_user or not email_pass:
        return False, "EMAIL_USER or EMAIL_PASS is empty in secrets."

    if not recipient_email or "@" not in recipient_email:
        return False, "Please enter a valid recipient email address."

    # Build email
    subject, html_body = _build_email_body(patient_name, center_name, clinician_name, language)

    msg = MIMEMultipart("mixed")
    msg["From"] = email_user
    msg["To"] = recipient_email
    msg["Subject"] = subject

    # HTML body
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    # PDF attachment
    pdf_attachment = MIMEApplication(pdf_bytes, _subtype="pdf")
    pdf_attachment.add_header(
        "Content-Disposition",
        "attachment",
        filename=pdf_filename,
    )
    msg.attach(pdf_attachment)

    # Send via Gmail SMTP
    try:
        context = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.login(email_user, email_pass)
            server.sendmail(email_user, recipient_email, msg.as_string())
        return True, f"Report successfully sent to {recipient_email}."

    except smtplib.SMTPAuthenticationError:
        return False, (
            "Gmail authentication failed. "
            "Please check your EMAIL_USER and EMAIL_PASS. "
            "If using Gmail, ensure you are using an App Password, not your regular password."
        )
    except smtplib.SMTPRecipientsRefused:
        return False, f"Recipient address '{recipient_email}' was refused by the mail server."
    except smtplib.SMTPException as e:
        return False, f"SMTP error: {str(e)}"
    except Exception as e:
        return False, f"Unexpected error sending email: {str(e)}"
